### ISSUE TITLE
test

### ISSUE THREAD

**Issue by hajimental** [hajimental/dotFiles#1]
mail test

**Comment by hajimental** [comment]
test

**Comment by h-oizumi** [comment]
en: test TEST test
ja: てすと テスト ＴＥＳＴ

大泉 一 <h.oizumi@gigei.jp>
株式会社 日本技芸
〒104-0061
東京都中央区銀座2-15-2 東急銀座二丁目ビル
TEL:03-4582-6073 FAX:03-4582-6071

2015-03-03 13:53 GMT+09:00 hajimental <notifications@github.com>:

**Comment by h-oizumi** [comment]
reply@reply.github.com 様

先ほど暗号化した電子メールを送信致しました。
つきましては、下記のパスワードにて暗号化を解除し、
閲覧いただくようお願い申し上げます。

件名 : Re: [dotFiles] test (#1)

パスワード : 9g5pFRbCGne2yjBX

よろしくお願いします。

**Comment by h-oizumi** [comment]
てすと出来た。
タイムラグ有り

**Comment by hajimental** [comment]
画像添付テスト

**Comment by hajimental** [comment]
@h-oizumi 
test
